name: solar_datepicker
description: Date Picker for persian date (solar / jalali / shamsi date).
version: 1.0.3
homepage: https://github.com/EhsnJmli/solar_datepicker

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shamsi_date: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: